use_frameworks!

platform :ios, '10.0'

target 'RYTransitioningDelegateSwift_Example' do
  pod 'RYTransitioningDelegateSwift', :path => '../'

  target 'RYTransitioningDelegateSwift_Tests' do
    inherit! :search_paths

    
  end
end
